<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentProcessing.Core\DocumentProcessing.Core.csproj" />
    <ProjectReference Include="..\DocumentProcessing.Engine\DocumentProcessing.Engine.csproj" />
    <ProjectReference Include="..\DocumentProcessing.Pdf\DocumentProcessing.Pdf.csproj" />
  </ItemGroup>

</Project>
